version: "3.2"
services:
  localstack:
    # https://hub.docker.com/r/gresau/localstack-persist
    image: gresau/localstack-persist:3.0.2
    container_name: localstack
    ports:
      - "4563-4599:4563-4599"
      - "8080:8080"
    environment:
      - DEBUG=1
    volumes:
      - "./localstack-data:/persisted-data"
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
  terraform-init:
    image: hashicorp/terraform:${TERRAFORM_VERSION}
    container_name: terraform-init
    depends_on:
      localstack:
        condition: service_healthy
    working_dir: /bootstrap
    volumes:
      - "./bootstrap:/bootstrap"
    command: init
  terraform-apply:
    image: hashicorp/terraform:${TERRAFORM_VERSION}
    container_name: terraform-apply
    depends_on:
      terraform-init:
        condition: service_completed_successfully
    working_dir: /bootstrap
    volumes:
      - "./bootstrap:/bootstrap"
    command: apply -auto-approve
    network_mode: "host"
  wait:
    image: alpine
    depends_on:
      terraform-apply:
        condition: service_completed_successfully
    command: sleep 5
