version: "3.2"
services:
  localstack:
    # https://hub.docker.com/r/gresau/localstack-persist
    image: gresau/localstack-persist:3.0.2
    container_name: localstack
    ports:
      - "4563-4599:4563-4599"
      - "8080:8080"
    environment:
      - DEBUG=1
    volumes:
      - "./localstack-data:/persisted-data"
    healthcheck:
      test: curl --fail http://localhost:4566 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
