name: Destroy ephemeral PR deployment

on:
  pull_request:
    types: [ closed ]

jobs:
  terraform-destroy-pr-deployment:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set workspace name
        id: set-workspace
        run: echo "workspace=456_us-east-1_dev_pr-${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Find existing PR ${{ github.event.number }} comment with ${{ steps.set-workspace.outputs.workspace }} deployment details
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This PR has been deployed to `${{ steps.set-workspace.outputs.workspace }}` via ${{ github.server_url }}/${{ github.repository }}/actions/runs
          direction: last

      - name: Use PR ${{ github.event.number }} comment to determine GitHub Actions run ID that created ${{ steps.set-workspace.outputs.workspace }} deployment
        uses: actions/github-script@v7
        id: run-id
        with:
          script: |
            const commentParts = '${{ steps.find-comment.outputs.comment-body }}'.split(' ');
            const runUrlParts = commentParts[commentParts.length - 1 ].replaceAll('.', '').split('/');
            return runUrlParts[runUrlParts.length - 1];
          result-encoding: string

      - name: Determine localstack-data artifact name generated from prior run
        id: artifact-name
        run: echo "artifact-name=localstack-data-${{ steps.set-workspace.outputs.workspace }}" >> $GITHUB_OUTPUT

      - name: Download persisted localstack data generated from prior run ID ${{ steps.run-id.outputs.results }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: localstack-data-tar
          run-id: ${{ steps.run-id.outputs.result }}
          github-token: ${{ github.token }}

      - name: Untar localstack data to localstack-data directory
        run: tar xf localstack-data-tar/${{ steps.artifact-name.outputs.artifact-name }}.tar --directory .

      - name: Start localstack mock AWS environment
        run: make start-localstack

      - name: Issue GET request to ${{ steps.set-workspace.outputs.workspace }} Terraform state at ${{ steps.set-workspace.outputs.workspace }}-specific S3 endpoint
        run: curl "http://localhost.localstack.cloud:4566/tf-workspaces-demo/env:/${{ steps.set-workspace.outputs.workspace }}/terraform.tfstate"

      - name: Set up tfenv
        uses: rhythmictech/actions-setup-tfenv@v0.1.2

      - name: Terraform destroy ${{ steps.set-workspace.outputs.workspace }}
        run: make destroy WORKSPACE=${{ steps.set-workspace.outputs.workspace }}

      - name: Create PR ${{ github.event.number }} comment with ${{ steps.set-workspace.outputs.workspace }} destruction details
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: 👋 Destroyed `${{ steps.set-workspace.outputs.workspace }}` via ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
