name: Pull Request

on:
  #pull_request:
  push:

jobs:
  set-up:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.set-matrix.outputs.workspaces }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up tfenv
        uses: rhythmictech/actions-setup-tfenv@v0.1.2

      - name: Set Terraform workspaces matrix
        id: set-matrix
        run: echo "workspaces=$(jq -c . < ./workspaces.json)" >> $GITHUB_OUTPUT

  terraform-plan:
    runs-on: ubuntu-latest
    needs: set-up
    strategy:
      matrix: ${{ fromJson(needs.set-up.outputs.workspaces) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up tfenv
        uses: rhythmictech/actions-setup-tfenv@v0.1.2

      - name: Start localstack mock AWS environment
        run: make up

      - name: Bootstrap localstack to have tf-workspaces-demo S3 bucket
        run: make bootstrap

      - name: Terraform plan ${{ matrix.account }}_${{ matrix.region }}
        run: make plan WORKSPACE="${{ matrix.account }}_${{ matrix.region }}"
